### ISSUE TITLE
Incorporate IETF area/workgroup information into static data here

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ietf-data#1]
We have to move the content of IETF area/workgroup lists to this new location.

Basically this content needs to be moved into GitHub Actions in this current repo:
https://github.com/metanorma/metanorma-ietf/blob/79f3c0faae12be4ae7852b2ecd6b6c968fe8122f/lib/asciidoctor/ietf/validate.rb#L37-L90

We can use a GHA workflow with cron to update the data here.

Corresponding issue in metanorma-ietf:
https://github.com/metanorma/metanorma-ietf/issues/156

**Comment by ronaldtse** [comment]
Ping @CAMOBAP @andrew2net would you be free to do this? I wonder if @andrew2net has more experience with this.

**Comment by CAMOBAP** [comment]
I'm ready to take it

@ronaldtse @opoudjis maybe you can point to similar `data` gem ? Should it just contain json or some extra logic too?

**Comment by ronaldtse** [comment]
@CAMOBAP Just JSON or YAML would be great. Only content, no logic needed here. The logic is to be updated in the metanorma-ietf code.

**Comment by CAMOBAP** [comment]
- [x] first gem pushed
- [x] `check_update` workflow implemented, I will check how it works

Moving to metanorma/metanorma-ietf#156 and will close once check_update` workflow passed

**Comment by ronaldtse** [comment]
@CAMOBAP Thanks! Just checking to see if there would be an issue with packed-mn on this line:

https://github.com/metanorma/metanorma-ietf-data/blob/7d0cfd9785b2e52d8c2bf9955213d4956aedd6f2/lib/metanorma/ietf/data/workgroups.rb#L7

**Comment by ronaldtse** [comment]
@CAMOBAP also, we do want to have a non-Gem format of data because it allows non-Ruby code to also fetch that information.

**Comment by CAMOBAP** [comment]
@ronaldtse https://raw.githubusercontent.com/metanorma/metanorma-ietf-data/main/lib/metanorma/ietf/data/workgroups.json is always available for such purpose. Let me know if there is a better way to accomplish this

**Comment by CAMOBAP** [comment]
> Thanks! Just checking to see if there would be an issue with packed-mn on this line

@ronaldtse good catch but! I didn't think about it.

I think it should not because we use Ruby's API for file manipulation i.e. `File.read` which is memfs-aware

**Comment by CAMOBAP** [comment]
looks complete

**Comment by ronaldtse** [comment]
Thanks!
